'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Goods', [
      {
        title: 'Брошь',
        description: 'Брошь в виде трекозы',
        exchange: 'Перстень',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 1,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Ручка',
        description: 'Стильная синяя ручка',
        exchange: 'Ластик',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 2,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Перстень',
        description: 'перстень-печатка',
        exchange: 'Подвеска или брошь',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 3,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Пеноблок',
        description: 'обычный пеноблок, остался от постройки дома.',
        exchange: 'Инструмент для ухода за садом',
        city: 'Саратов',
        status: 'active',
        isModerate: true,
        userId: 1,
        categoryId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Секатор',
        description: 'Секатор для ухода за посаженными деревьями',
        exchange: 'Телефон',
        city: 'Иркутск',
        status: 'active',
        isModerate: true,
        userId: 2,
        categoryId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Графический планшет',
        description: 'ЧУДО ТЕНИКИ!',
        exchange: 'Хочу АВТОМОБИИИИЛЬ!!!!',
        city: 'Иркутск',
        status: 'active',
        isModerate: true,
        userId: 1,
        categoryId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Батарека',
        description: 'Батарейка - крона',
        exchange: 'Телефон',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 3,
        categoryId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Фары Porsche ',
        description: 'Фары от порш каен. Мелочевку не предлагать! Обменяюсь на МАШИНУ',
        exchange: 'Автомобиль',
        city: 'Иркутск',
        status: 'active',
        isModerate: true,
        userId: 2,
        categoryId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Держатель для телефона ',
        description: 'Держатель для телефона в авто',
        exchange: 'Балонный ключ',
        city: 'Саратов',
        status: 'active',
        isModerate: true,
        userId: 1,
        categoryId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Автомобиль ВАЗ',
        description: 'Моя Вишневая девятка! Отличный вариант для первой машины. Делаю обмен на что-нибудь стоящее',
        exchange: '',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 3,
        categoryId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Балонный Ключ',
        description: 'Машину продал - балонник остался, сделаю обмен на что-нибудь',
        exchange: '',
        city: 'Иркутск',
        status: 'active',
        isModerate: true,
        userId: 2,
        categoryId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Телефон',
        description: 'Чоткая труба, музыка ахонь, 60мб памяти - качай, закачаешься',
        exchange: 'Приставка Денди',
        city: 'Иркутск',
        status: 'active',
        isModerate: true,
        userId: 2,
        categoryId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Телефон NOKlA',
        description: 'Для истинных ценителей подручных средст на все случаи жизни',
        exchange: 'Телефон с цветным дисплеем',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 3,
        categoryId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Клетка для попугая',
        description: 'Поменяюсь на клетку побольше. Мой попугай заметно подрос',
        exchange: 'Большая клетка для попугая',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 4,
        categoryId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Питон',
        description: 'Отдам взрослого питона, кормить нужно не часто, раз в месяц. После того как от меня ушла жена решил отдать его в добрые руки - обмен на котиков.',
        exchange: 'Котенок',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 3,
        categoryId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Шлейка для котов',
        description: 'Предлагайте',
        exchange: '',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 3,
        categoryId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Футболка Pokemon',
        description: 'Даю на обмен коллекционную футболку размер М',
        exchange: 'Фишки покемон',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 4,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Игрушка Pokemon',
        description: 'Легендарный покемон ',
        exchange: 'Карты Pokemon',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 4,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Рулон обоев',
        description: ' Светлые.Хватит на 4м2 ',
        exchange: 'Обои',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 6,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Обои под покраску',
        description: 'Не нравится оттенок - меняю на другой',
        exchange: 'Обои под покраску',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 6,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Коллекция скриншотов',
        description:'Питомцы на собраниях. Коллекция мне очень дорога и я готова этим счастьем поделиться',
        exchange: 'Кофе',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 7,
        categoryId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Коллекция мемчков',
        description:'Родненькие, собранные своими руками',
        exchange: 'Адаптивная верстка страницы',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 5,
        categoryId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
