'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Goods', [
      {
        title: 'Цыганские игрушки',
        description: 'Дети выросли, уже нужны игрушки посерьезнее',
        exchange: 'Надувной бассейн',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 7,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Индийский чай',
        description: 'Собран с лучшийх плантаций Индии моими друзьями. Чая много, могу меняться на что угодно',
        exchange: 'Без разницы',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 1,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Индийский кофе',
        description: 'Кофе божественный!',
        exchange: 'Чай не предлагать! Его полно',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 1,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Худи Elbrus',
        description: 'Предлагаю на обмен мерч лучшего буткемпа в России. В наличии есть худи, футболки, толстовки, бейсболки и даже неоновая вывеска. Больше фото по запоросу',
        exchange: '',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 2,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Секатор',
        description: 'Секатор для ухода за посаженными деревьями',
        exchange: 'Телефон',
        city: 'Иркутск',
        status: 'active',
        isModerate: true,
        userId: 5,
        categoryId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Графический планшет',
        description: 'ЧУДО ТЕНИКИ!',
        exchange: 'Хочу АВТОМОБИИИИЛЬ!!!!',
        city: 'Иркутск',
        status: 'active',
        isModerate: true,
        userId: 5,
        categoryId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Доска для серфа',
        description: 'Немного б/у, но катать можно. Нахожусь на Бали, могу отправить в любую точку мира',
        exchange: 'Курс по React Native',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 3,
        categoryId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Фары Porsche ',
        description: 'Фары от порш каен. Мелочевку не предлагать! Обменяюсь на МАШИНУ',
        exchange: 'Автомобиль',
        city: 'Иркутск',
        status: 'active',
        isModerate: true,
        userId: 8,
        categoryId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Держатель для телефона ',
        description: 'Держатель для телефона в авто',
        exchange: 'Балонный ключ',
        city: 'Саратов',
        status: 'active',
        isModerate: true,
        userId: 1,
        categoryId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Автомобиль ВАЗ',
        description: 'Моя Вишневая девятка! Отличный вариант для первой машины. Делаю обмен на что-нибудь стоящее',
        exchange: '',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 5,
        categoryId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'ВАЗ 2102',
        description: 'Отдам лялю в добрые руки. Машина в идеальном состоянии. Все агрегаты рабочие. Вся история есть на драйве',
        exchange: 'В идеале на трешку в Москве',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 2,
        categoryId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Телефон',
        description: 'Чоткая труба, музыка ахонь, 60мб памяти - качай, закачаешься',
        exchange: 'Приставка Денди',
        city: 'Иркутск',
        status: 'active',
        isModerate: true,
        userId: 8,
        categoryId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Телефон NOKlA',
        description: 'Для истинных ценителей подручных средст на все случаи жизни',
        exchange: 'Телефон с цветным дисплеем',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 8,
        categoryId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Клетка для попугая',
        description: 'Осталась клетка от волнистых попугаев. Малявки все померли. Купил себе большого белохвостого какаду (живет 60 лет).',
        exchange: 'Ну хз. На рой покемонов мб',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 4,
        categoryId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Питон',
        description: 'Отдам взрослого питона, кормить нужно не часто, раз в месяц. Обмен на котиков.',
        exchange: 'Котенок',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 8,
        categoryId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Шлейка для котов',
        description: 'Думал кота заведу, а купил какаду',
        exchange: 'Желательно на корм для крупных попугаев',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 4,
        categoryId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Футболка Pokemon',
        description: 'Даю на обмен коллекционную футболку размер М',
        exchange: 'Фишки покемон',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 4,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Игрушка Pokemon',
        description: 'Легендарный покемон ',
        exchange: 'Карты Pokemon',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 4,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Обои',
        description: 'Качественные итальянские виниловые обои. Разные расцветки. Я бы даже сказал целая коллекция',
        exchange: 'Надоели. Обменяю на другую коллекцию',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 6,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Обои под покраску',
        description: 'Не нравится оттенок - меняю на другой',
        exchange: 'Обои под покраску',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 6,
        categoryId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Коллекция скриншотов',
        description:'Питомцы на собраниях. Коллекция мне очень дорога, но кофе важнее, поэтому готова этим счастьем поделиться',
        exchange: 'Кофе',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 7,
        categoryId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Мемасики',
        description:'Родненькие, собранные своими руками',
        exchange: 'Поменяю на все для адаптива',
        city: 'Москва',
        status: 'active',
        isModerate: true,
        userId: 5,
        categoryId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
